name: kimmy
description: kimmy app gui.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartssh2: ^2.7.3
  easy_isolate: ^1.3.0
  get: ^4.6.5
  hive: ^2.2.3
  date_format: ^2.0.4
  shared_preferences: ^2.0.10
  path_provider: ^2.0.7
  file_picker: ^5.2.2
#  file_selector: ^0.9.2
  json_annotation: ^4.6.0
  flutter_spinkit: ^5.1.0
  encrypt: ^5.0.1
  flutter_swipe_action_cell: ^3.0.4
  bot_toast: ^4.0.3
#  source_gen: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

